version: '3'

services:
  web:
    build: .
    ports: 
      - "4000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:4.0.1-alpine
    read_only: true
    user: redis